name: Deploy Python Code to AWS Lambda
author: dpo
description: Deploy python 3.8 code to AWS Lambda, lightning quick builds!
inputs:
  function_name:
    description: the Lambda function name
    required: true
  working_directory:
    description: the Lambda function directory
    required: true
  runtime:
    description: the Lambda function runtime
    required: true
  role:
    description: the Lambda function IAM role
    required: true
  handler:
    description: the Lambda function handler
    required: true
  memory:
    description: the Lambda function memory size in MB
    required: true
  timeout:
    description: the Lambda function time limit in seconds
    required: true
  env_variables:
    description: Environment variables in the format {var1=value1,var2=value2}
    required: false
  vpc_config:
    description: VPC configuration in the format SubnetIds=string,string,SecurityGroupIds=string,string
    required: false
  layers:
    description: Lambda layers ARN
    required: false
  tags:
    description: Tags in the format Key1=Value1,Key2=Value2
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.function_name }}
    - ${{ inputs.working_directory }}
    - ${{ inputs.runtime }}
    - ${{ inputs.role }}
    - ${{ inputs.handler }}
    - ${{ inputs.layers }}
    - ${{ inputs.memory }}
    - ${{ inputs.timeout }}
    - ${{ inputs.env_variables }}
    - ${{ inputs.tags }}
branding:
  icon: "cloud-lightning"
  color: "orange"
